version: '3.5'
services:
 zabbix-server:
  image: zabbix/zabbix-server-mysql:alpine-6.0-latest
  ports:
  - "10051:10051"
  volumes:
  - /etc/localtime:/etc/localtime:ro
  - /etc/timezone:/etc/timezone:ro 
  - alertscripts:/usr/lib/zabbix/alertscripts:ro
  - externalscripts:/usr/lib/zabbix/externalscripts:ro
  - export:/var/lib/zabbix/export:rw
  - modules:/var/lib/zabbix/modules:ro
  - enc:/var/lib/zabbix/enc:ro
  - ssh_keys:/var/lib/zabbix/ssh_keys:ro
  - mibs:/var/lib/zabbix/mibs:ro
  - snmptraps:/var/lib/zabbix/snmptraps:rw
  links:
  - mysql-server:mysql-server
  restart: unless-stopped
  ulimits:
   nproc: 65535
   nofile:
    soft: 20000
    hard: 40000
  deploy:
   resources:
    limits:
      cpus: '0.70'
      memory: 1G
    reservations:
      cpus: '0.5'
      memory: 512M
  env_file:
  - .env_db_mysql
  - .env_srv
  secrets:
  - MYSQL_USER
  - MYSQL_PASSWORD
  - MYSQL_ROOT_USER
  - MYSQL_ROOT_PASSWORD
  depends_on:
  - mysql-server
  networks:
   zbx_net_backend:
     aliases:
     - zabbix-server
     - zabbix-server-mysql
     - zabbix-server-alpine-mysql
     - zabbix-server-mysql-alpine
   zbx_net_frontend:
  stop_grace_period: 30s
  sysctls:
  - net.ipv4.ip_local_port_range=1024 65000
  - net.ipv4.conf.all.accept_redirects=0
  - net.ipv4.conf.all.secure_redirects=0
  - net.ipv4.conf.all.send_redirects=0
  labels:
   com.zabbix.description: "Zabbix server with MySQL database support"
   com.zabbix.company: "Zabbix LLC"
   com.zabbix.component: "zabbix-server"
   com.zabbix.dbtype: "mysql"
   com.zabbix.os: "alpine"
  logging:
   driver: ${ZABBIX_SERVER_LOG_DRIVER:-json-file}
   options:
    max-size: ${ZABBIX_SERVER_LOG_MAX_SIZE:-2m}
    max-file: ${ZABBIX_SERVER_LOG_MAX_FILE:-2}

 zabbix-web-nginx-mysql:
  image: zabbix/zabbix-web-nginx-mysql:alpine-6.0-latest
  expose:
  - '8080'
  volumes:
  - /etc/localtime:/etc/localtime:ro
  - /etc/timezone:/etc/timezone:ro
  - nginx:/etc/ssl/nginx:ro
  - web-modules:/usr/share/zabbix/modules/:ro
  deploy:
   resources:
    limits:
      cpus: '0.70'
      memory: 512M
    reservations:
      cpus: '0.5'
      memory: 256M
  env_file:
  - .env_db_mysql
  - .env_web
  environment:
  - VIRTUAL_PORT=8080
  restart: unless-stopped
  secrets:
  - MYSQL_USER
  - MYSQL_PASSWORD
  depends_on:
  - mysql-server
  - zabbix-server
  healthcheck:
   test: ["CMD", "curl", "-f", "http://localhost:8080/"]
   interval: 10s
   timeout: 5s
   retries: 3
   start_period: 30s
  networks:
   zbx_net_backend:
    aliases:
    - zabbix-web-nginx-mysql
    - zabbix-web-nginx-alpine-mysql
    - zabbix-web-nginx-mysql-alpine
   zbx_net_frontend:
   frontend:
  stop_grace_period: 10s
  sysctls:
  - net.core.somaxconn=65535
  labels:
   com.zabbix.description: "Zabbix frontend on Nginx web-server with MySQL database support"
   com.zabbix.company: "Zabbix LLC"
   com.zabbix.component: "zabbix-frontend"
   com.zabbix.webserver: "nginx"
   com.zabbix.dbtype: "mysql"
   com.zabbix.os: "alpine"
  logging:
   driver: ${ZABBIX_WEB_SERVER_LOG_DRIVER:-json-file}
   options:
    max-size: ${ZABBIX_WEB_SERVER_LOG_MAX_SIZE:-2m}
    max-file: ${ZABBIX_WEB_SERVER_LOG_MAX_FILE:-2}

 mysql-server:
  image: mysql:8.0
  cap_add:
  - SYS_NICE  # CAP_SYS_NICE
  expose:
  - '3306'
  command:
  - mysqld
  - --character-set-server=utf8mb4
  - --collation-server=utf8mb4_bin
  - --skip-character-set-client-handshake
  - --default-authentication-plugin=mysql_native_password
  volumes:
  - mysqldb:/var/lib/mysql:rw
  env_file:
  - .env_db_mysql
  secrets:
  - MYSQL_USER
  - MYSQL_PASSWORD
  - MYSQL_ROOT_PASSWORD
  restart: unless-stopped
  stop_grace_period: 1m
  networks:
   zbx_net_backend:
    aliases:
    - mysql-server
    - zabbix-database
    - mysql-database
  logging:
   driver: ${ZABBIX_MYSQL_SERVER_LOG_DRIVER:-json-file}
   options:
    max-size: ${ZABBIX_MYSQL_SERVER_LOG_MAX_SIZE:-2m}
    max-file: ${ZABBIX_MYSQL_SERVER_LOG_MAX_FILE:-2}

networks:
 frontend:
  driver: bridge
  driver_opts:
   com.docker.network.enable_ipv6: "false"
  external:
   name: frontend
 zbx_net_frontend:
  driver: bridge
  driver_opts:
   com.docker.network.enable_ipv6: "false"
  ipam:
   driver: default
   config:
   - subnet: 172.16.238.0/24
 zbx_net_backend:
  driver: bridge
  driver_opts:
   com.docker.network.enable_ipv6: "false"
  internal: true
  ipam:
   driver: default
   config:
    - subnet: 172.16.239.0/24

volumes:
 alertscripts:
 enc:
 export:
 externalscripts:
 mibs:
 modules:
 mysqldb:
 nginx:
 snmptraps:
 ssh_keys:
 web-modules:
 ssh-conf:
 robotkz:

secrets:
 MYSQL_USER:
  file: ./.MYSQL_USER
 MYSQL_PASSWORD:
  file: ./.MYSQL_PASSWORD
 MYSQL_ROOT_USER:
  file: ./.MYSQL_ROOT_USER
 MYSQL_ROOT_PASSWORD:
  file: ./.MYSQL_ROOT_PASSWORD
